version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: none  # ⬅️ ВАЖНО: не перезапускать автоматически
    environment:
      POSTGRES_DB: mainDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnamilegacy/kafka:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: none  # ⬅️ ВАЖНО: не перезапускать автоматически
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  core-api:
    image: core-api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: none  # ⬅️ ВАЖНО: не перезапускать автоматически
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka

  notifications:
    image: notifications:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: none  # ⬅️ ВАЖНО: не перезапускать автоматически
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=development
    depends_on:
      - kafka